"""Add location field to ProductionLine model

Revision ID: 01073078d65e
Revises: a8d810b6e734
Create Date: 2025-04-28 00:46:36.626967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01073078d65e'
down_revision = 'a8d810b6e734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacity_period', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.drop_column('capacity_period')
        batch_op.drop_column('capacity_unit')

    # ### end Alembic commands ###
