"""Add is_active field to ProductionStep

Revision ID: 1d91e47b65e9
Revises: cc4100dc30cd
Create Date: 2025-04-26 03:39:43.081540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d91e47b65e9'
down_revision = 'cc4100dc30cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_rep_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_orders_sales_rep', 'sales_representatives', ['sales_rep_id'], ['id'])




    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_rep_id')

    # ### end Alembic commands ###
