"""Add category_type to Category model

Revision ID: 63bb482bb312
Revises: d8ff05203df4
Create Date: 2025-04-07 08:58:13.539341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bb482bb312'
down_revision = 'd8ff05203df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_batch_production_order', 'production_orders', ['production_order_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('production_order_id')

    # ### end Alembic commands ###
