"""Add created_at to customer_interactions

Revision ID: 801b45b94ff1
Revises: a293a909387d
Create Date: 2025-04-26 16:00:03.568469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801b45b94ff1'
down_revision = 'a293a909387d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('interaction_type',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('follow_up_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_customer_interactions_users', 'users', ['created_by'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_interactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('follow_up_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('interaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_column('created_by')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
