"""Add cash_account_id to SalesPayment model

Revision ID: 82fa44fa074a
Revises: 01073078d65e
Create Date: 2025-05-02 14:21:11.476169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82fa44fa074a'
down_revision = '01073078d65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_returns')
    with op.batch_alter_table('packaging_material_usage', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cash_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'cash_accounts', ['cash_account_id'], ['id'])

    with op.batch_alter_table('sales_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cash_accounts', ['cash_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cash_account_id')

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('cash_account_id')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('packaging_material_usage', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('product_returns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sales_order_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('return_reason', sa.VARCHAR(length=9), nullable=True),
    sa.Column('return_status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('refund_amount', sa.FLOAT(), nullable=True),
    sa.Column('return_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.ItemID'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.SalesOrderID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
