"""Add created_at to customer_interactions

Revision ID: 9c121fec2aee
Revises: 801b45b94ff1
Create Date: 2025-04-26 18:57:57.098460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c121fec2aee'
down_revision = '801b45b94ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_details', schema=None) as batch_op:
        batch_op.alter_column('ItemID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_details', schema=None) as batch_op:
        batch_op.alter_column('ItemID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
