"""Description of changes

Revision ID: a293a909387d
Revises: 1d91e47b65e9
Create Date: 2025-04-26 03:45:43.056261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a293a909387d'
down_revision = '1d91e47b65e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_rep_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_orders_sales_representatives', 'sales_representatives', ['sales_rep_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_orders_sales_representatives', type_='foreignkey')
        batch_op.drop_column('sales_rep_id')

    # ### end Alembic commands ###