"""Add location field to ProductionLine model

Revision ID: a8d810b6e734
Revises: 9c121fec2aee
Create Date: 2025-04-28 00:43:47.022165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d810b6e734'
down_revision = '9c121fec2aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', name='sales_order_status_enum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled', name='sales_order_status_enum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('production_lines', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
