"""Add is_active field to ProductionStep

Revision ID: cc4100dc30cd
Revises: 63bb482bb312
Create Date: 2025-04-26 02:26:49.746315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4100dc30cd'
down_revision = '63bb482bb312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_steps', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
