"""Add category_type to Category model

Revision ID: d8ff05203df4
Revises: 5500d93b74fa
Create Date: 2025-04-07 03:02:26.487357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ff05203df4'
down_revision = '5500d93b74fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ProductionRunID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_batch_production_run', 'production_runs', ['ProductionRunID'], ['ProductionRunID'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', sa.Enum('FinalProduct', 'Packaging', 'RawMaterial', 'IntermediateProduct', name='category_type_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category_type')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_batch_production_run', type_='foreignkey')
        batch_op.drop_column('ProductionRunID')

    # ### end Alembic commands ###
